xnRace = xnRace or {}


-- UGC Content URLS
xnRace.RaceTable = {
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0126/DaHBvkP7dEKCdy1qPA78Ew/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0822/83axdSaAS02J-Z0e1df-jw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0893/oeWgDf7GN0CkLszt8JRjfQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2013/0shqLVDjd0qVDv-CHUv8ew/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2139/tfkmPM0V00uKGboIWAbk4g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2314/mZ0PcmK-lUusdC3d_db6CA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2525/Y-Vv0cIN2Uqxx3xR2PALag/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2688/od2MHwZ-z0y_oxYOCJiadw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3054/B6r3Irqu8UuE5CyqpI512A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3134/JrbYCpLGdUuU2rhvsSW2wQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3793/o8yNzLS0O02Ld5w_h8CKtw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3874/ddHtd5ObCUulYYRG6CnSzw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3941/A7jqgI-h9k2au7dj7gRsmw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3981/rtNlyMjwx02EehGBGELmFA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4061/BnJdo30Ppkaknghd3xD00A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4151/zQMPw-QFBkWXsA5yrEHiBg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4831/gAxdwhFiPUmW30v1GDKSeg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4846/YmiHpz6bBU2g78fo4GrJng/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4870/WAyVbig6OkSMbD7lapk84w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4998/vyTABS5xR06--t_w6e9t0w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5403/8PrF1PzohUGVERk5IH68Ew/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5499/akcrtIfrH0ioverkdkdD0A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5811/e-ICTCVrgUSCdDjRyg3x9w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6062/-DkdoRcQK0SZ04rrxvOjlA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6252/3imRTH7ehEWmDwW2-mncmg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6477/kxV5YVMQSEKY04MseoEmFA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6518/tQArg4sDt0-ATPwkAa4UcA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6681/s8A3DDORE0CN5zUKPB4dLQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6684/eV8RvueYtUyboNpN_7UWag/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7474/2Y2HGHWTb0i_raVNjGnoXg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7614/kyMIMs7vykO8A4W5eFlqGg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7862/j9KIsGgp0keTks4rjlqoTg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7980/JwAm0wWMbkmHa_TKIoau7w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8023/mPCp2HY4VUOpJOo3XNyLJQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8098/JnlKjCjByEmNdTbWvzppZQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8349/rN2-NtpRNEuCccGeEW7I5g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8354/vLWtKE-4yUed3CDCX_Ry8Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8469/8EC28lyqjUC4QbYzyAs7_Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8523/159dEmF19k69-8RrYQSXbg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8573/0sQw52xaekGDJIglmG8TUw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8880/p5dR1Huzmk2W492a764yvg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8910/_qVEnMQAFEKQJENdLWw6HA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9015/xHqN1GOv1E2mcmcpaKOJHQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9093/7dvLnQs1ykyVpRwA1X7U7w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9262/g9pM0C_DoUan2t_kzpL0lA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9899/zZYDkgMl70OUOKlj9BsLtA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9997/o2shtc0NgUK1DSs8N4D0pw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6861/raJFAGN0J0CWla3Tz8YnGg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5454/9g4xRe6tSEuwkR03KdpOcg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2255/oe9WgY0fZEKo1bXb1bWuJQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2882/RUGT8IaCAEeLUhhlfCDCGw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0127/OfePZemz9ECeScjVHxzgVw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4317/wxLNlzk2o06ejO_GcDMnzg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0647/Z412JInUSUmlOlyNNrItTw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6235/AQNQ8cibykygYKprtKS2PQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8005/D6gI11GYO0Opa4kF7e7Pfg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3015/uGoPvS-PXEydYX7AWX_Wbw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9885/_fIf6ALoTk-epof_P3VoDA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7325/Ae0vz5vh602H_IQGj41etw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5726/V7cWpI40WE-vAwT7Unz0og/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9193/iRQjq-UwyUWUdkLFAHWNDw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1913/Xvj11ve-DkqSUKatUq5P8w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4327/DK_G439c906eO-JsIMOINQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2597/f6YabtzUUkOKrXHCxXL2Ag/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3139/bNG2E2y_LEeXxBEjAYqUnQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3392/1ArLVLbMHEW6KQTtFE7QXQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4328/Zut07BDxZker-13I9YpsYw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0315/4pddP7YNdEmdloewxaOVlA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2125/8SdVUCCCJEi13iD5y0wOwA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8123/thFZh44zzU28pQsrnL6Cgw/0_0_en.json",
    --"https://prod.cloud.rockstargames.com/ugc/gta5mission/9791/oj3YTsvfAUes1_kNv9Iycw/0_0_en.json", -- BROKENURL
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6138/62pmdrswgku6wEdi45s3tw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8838/mAyR4kMvpUuAY8RRiO6a6A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5396/H0UPrk10lUmBbmxIpKwcxg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7290/Cnv3BTWRLES1N2bTF5nzmQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9741/qbTZ-7llX0CI-2jGLHpthw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8752/KsQyYoPomE2Ov5sqC0n4dA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4643/ocDrNUhoiEKZb29cMOKf5g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3075/Bso_Z23S9UWDvMAwMuwpUw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2816/qwSIyw_qTkGKuCYxiCjyww/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0925/-iQBCouj8k6UQFNHG7vP8w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0729/BPybuOZZI0mTskKSoSQZKQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6889/_s7fIPxJCU2gviRs8R1Spg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2235/FN9Bi81zL0-UrLBglhCe9A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3157/zHoELGi9Y026kmcBKH7_gg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1383/rcCpgAeoaUGhmKLciHXQQg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4866/CpvYY8u29Em4QpPpDxofKg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7123/mTqBwycLbUuzWME81g9egw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0108/t9OCfIlBEkuno2_w_TnYPg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8973/i_2RxIA-G0iq1OGbErp-8w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1421/6JknS5ducESN7tUtuOt3uA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7105/BOKa_blyakS6_cHtIAMllw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6463/hJwKExP6fEaieYdQeSTNPA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6477/B5xTMEa6CUKrW9YBTdxUPg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3610/KG4DSHKibEWRNdy2_7dKyA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1237/TN5T8jpdVUK_XnxIcBLi2w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4757/p9sLZOfzkU-Vg13JYHDjwQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9014/EO8YukLilECobCYUP8T2RA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8925/u6sJtAgJQkaUWphczHjPCg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9629/7XYHF0Bd0Emb3Iy4fd_iLQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1876/rhxGov0MvUSu8wTQITFU4A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1830/Z5Z7z_LQc0WJU6Jqq1P-Kw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0607/aJ2tJmGgDUamNGmGoIpkPA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0657/QSH2E_KLmkuBNX5l6m7PbQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9915/qNYygy5zx06rHqSaccBbhw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0336/BmZlQFoywk-caVw_amwjhQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5546/uIrNGhYmjUmmMjwUTUDprg/0_0_en.json",
    --"https://prod.cloud.rockstargames.com/ugc/gta5mission/6516/8baoG7FrN0mAUVdlvrV-vw/0_0_en.json", -- BROKEN URL
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0489/a9KsBigMD0-ot1Y_E_6-rw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6999/-3cw8BVYqUKXU3RQvr60Fg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1683/nQNPEK_lOUOcFElUGICyGA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3598/u2NbEYLJYEi7gCqx1IQYXQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3901/NrTW72fgcEmQva7UCg4IPw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5969/P5ojMF12TUmTFwaCluaR2w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1942/_ClYvtLwf06ccYKyMxTQCQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3581/jKDP2OZhmUaOCTW6KLb3iA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6308/raNIbkom5ESGOsoev4421A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7916/iEW1wBNGf0aOqlyE52ARgA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1154/snPwWLDr70WXF-RMCU7UOQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7887/FdWDgFUd1kK9aee_VuS4lg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0389/HrC62ETowUWTh9yldM57xQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4499/2U7OyNEV80CsPYVnnuKmHA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1696/K0Jw079BHUuGoNV78eyFWg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1842/SYeGdOoGq0eW_7Jioz2sGA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6932/m2wwidHVoE6gCQVlZCm6yg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3334/4qM7QZ9ktUSTNHiLEqiDTg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3798/Vi0cIqxPSEKtTjiFsyE9Hg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3103/55Q2QmiDN0yo75xFK_RLyA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2675/7kNG1xApZ0iRTk3X8WsxcQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6236/N9fM0IA9HEK0UGwujL6IDQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0699/H_fHNiSKr0GsHhNPuqSumg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7287/we3XdYAa_0yh4nnRMLNyYA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7933/UVsJkzbpj0y5CCACxSCr0g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2292/gApuL7hc2kOHC5WL1hHTyg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4958/-zZCBEoSgkafWp_-OYLMxw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5439/p_rLB3vwrESvRP3-uC9BEQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3986/7yLAOozuEUSo83ND6u3ZAQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1827/x9MRJkGDmkyY9As8xJIv-Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4577/rfzjWrGWYUyCs23cc7bzMA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2760/7cklgyPo5kK6Bj5ZPH3BIA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4918/DUcMQiA9F0usLP88Isvo8A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6270/KSB03oYf90WpEEoFTHA6_w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/1970/l16MAbzMpUyeiw2P2sYypw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6838/OdV8udvooU-Xys4OgEIH6g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6122/023A4ql1K0yMSh_IeqOl7Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0269/l3_-Wagh9kqMOGLBxHpZ5Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0289/9zyNSstUP0SBrFNNFOy4qw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7414/97vyde9Ni0eKgyRWooo_SA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4996/mUqsX-nE4kO9ejrT_ha93Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4142/xzXoAlVFNEO97HEljWDmIQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4196/oMBjnsayr0SSYbPzZMI2Fw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5794/Dd_VSOY2NUioociKbT-__A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9772/w8JARktMq0eAIJg3mrY8zQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5829/Tnl3CgDcx0SIZ1GJC6DZ6Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6658/v7UUQWAvxk22BOYSunXUlw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8928/PkTMZri2Nka3kgsAq7_erg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5206/zHZol1258k6lbJKzK3e2Pw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0323/akf3A7fPr0ez6Nve9_A9Bg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8676/DTLmsOcu3UiKN3vWyX5zYQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6341/gF7HdfIrMUqolBp1Aq-KCQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7971/Ri-oMxlslUCfOE9_f_UcYw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8087/-C1l1ZqEyUa05PQ__tQW4Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7846/SDdJeGCMhk270rEb7SviqA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3106/lt3wgPQNdEeRT7ZErC5ESA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8165/Sud50ajBnkeN3JIBa8y-nQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6778/nAxy1xzn60OY8QxryfjlGw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6472/oBDnWG3dDkGaezjxspUz0Q/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8896/LjPUMru-Nk6B3SVuohthSw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8668/YJloMJ5jQUy_MXl4mM0aNg/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/9232/12QlI1BzD0a-gSArV274lw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5879/DCxYB0z9PECZjIHO3Wfs_w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0396/4am5qmSSZUG3VJeFPjSW3A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0801/bBIy9LChsk-bHNROt3qz9w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/2325/8iohBXT9nUuVqJXfxWMVWQ/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/3370/c-Zw8Gf48EKjc2iRzWgpZw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/5099/-DZcEtXvAkuaVsJl-d_0oA/0_0_en.json",
	"https://prod.cloud.rockstargames.com/ugc/gta5mission/2741/5x2WQUsROk-Dw98Vp3vsIA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6975/-OTbcaUpOUiapeazjNX3gw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/7218/RXKGckI-lESBLkN7Le9Z6A/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4315/am3vEVrqQkeU2hpTcIsu2g/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0849/JYvHr8fgJ0Ca5LC6JilFFA/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/8692/UXeyTn6KnEij3M8a9rOMtw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/6924/DUoe1NUcVEScONb3WrUm4A/0_0_en.json",
	"https://prod.cloud.rockstargames.com/ugc/gta5mission/3384/nMGmNqbm5065s3x3kFw0Vw/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/4091/TO5h9AcThkeDodbPdy3h5w/0_0_en.json",
    "https://prod.cloud.rockstargames.com/ugc/gta5mission/0142/88GbKq_vr0msY5_z-K96xg/0_0_en.json",
	-- 											
	-- Transform Races
	--
	-- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3541/7-eCO7kiMk-JheqIS-w_wg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/0011/J1spwwSDv0-LzUrt9GGRuQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/1405/ukw40LnlEkuFphxFyQqoUg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/0299/p-loU9BEwECcfIVthjV96w/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/1962/5Ot3Psmzw0qy1WOccRY9MA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6860/4pzkC6yO1UK5m5_lX1ORIg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/8036/-iCVOaz2yEO32R4g14W1WQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2122/t7inIHW7KEe7xThanQg8DA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2924/VUAC8PPsIEy_YvKh0-UndQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3239/80Awae4c3UG5fTGSUxAOOA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/5131/NoAH41FpvUyay6kP6Q0-1Q/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/4638/6Bq53qRQ4keYQNZLC92aRQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/4855/LITtInjPc0WN_bFHnNAcfw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/8868/Wl5HRWjPdE-eKX6Du_DPkQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3082/Tfk4-Cg4F0y0UzY7thGGbw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2109/GxSjIuIjRUCFzqUtsHsaAg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6250/fu0yReUJ8ka2VIuhaPAK5g/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6926/I6J9kqeB6EWqeGIFzh4Vsg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/4762/AcekqdAdk0qC2e95i-MV9Q/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3819/2sP0j5kqP0Oe6prWru0Qtw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3150/l9_UktzidUCkTadAfFaqxg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2878/Ag9UPp8zkUyihCnJ8qywRA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/5315/gOn5yUbusUS0NTsnLn9rLA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3089/4HPktrU5fEOjo61vuHQVjw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/0513/4_kfsTofq0KM9is1S2Sq-w/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3128/KE9C3AwvVUqleHhZi5Nm_g/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/1738/l4vF_nEkD0mhkNcKIDikTg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/9096/UQwoRyKZq0aRN1ohv7v2WQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/9746/qA6Wc5MJrkStRdYfcjuZ3g/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3861/7p3tOaQDGEuM3InCHQfEmQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3247/xyGXNWPXdUivnQ7CLmcSVw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/4273/JPjWCDwX2kmSRgONIu3owA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6319/SJ5qd7KFYk6eOIB4_lUHEQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/7081/LlgKpz1vpkq1oXnMZoDUaw/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/4237/P-PgOFGV1Eagjbyy0we18Q/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/3660/mXyu9ezy6ESxrolAuANlnA/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6416/WxOtmZSua0-kLzmvKTtLrg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/8348/B4zRd_FVlUW7gTOTlyLMdg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/1907/2m7ZGgePskK9gVOi88ewqg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/0723/659J9pz_XUaRvmstxs3HmQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2358/5Z88Sz-RXEmo2ygfVRveaQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/0883/TSrYyIzAIEurmFsCMVJl7Q/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/5723/asZuL1_7ME6I7SnzWLsvjg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/2596/sVslElXAdEmHbqKJSRSZdQ/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/6290/8lU-9Mf5_0WOr0lUwqW2fg/0_0_en.json",
    -- "https://prod.cloud.rockstargames.com/ugc/gta5mission/5828/rmFQErtCvkeIwoa0o71HEA/0_0_en.json",
}

xnRace.PlayerModels = {"mp_f_deadhooker","mp_f_stripperlite","mp_g_m_pros_01","mp_m_exarmy_01","mp_m_famdd_01","mp_m_fibsec_01","mp_m_shopkeep_01","mp_s_m_armoured_01","a_f_m_beach_01","a_f_m_bevhills_01","a_f_m_bevhills_02","a_f_m_bodybuild_01","a_f_m_business_02","a_f_m_downtown_01","a_f_m_eastsa_01","a_m_m_acult_01","a_m_m_afriamer_01","a_m_m_beach_01","a_m_m_beach_02","a_m_m_bevhills_01","a_m_m_bevhills_02","a_m_m_business_01","a_f_m_eastsa_02","a_f_m_fatbla_01","a_f_m_fatcult_01","a_f_m_fatwhite_01","a_f_m_ktown_01","a_f_m_ktown_02","a_f_m_prolhost_01","a_m_m_eastsa_01","a_m_m_eastsa_02","a_m_m_farmer_01","a_m_m_fatlatin_01","a_m_m_genfat_01","a_m_m_genfat_02","a_m_m_golfer_01","a_f_m_salton_01","a_f_m_skidrow_01","a_f_m_soucentmc_01","a_f_m_soucent_01","a_f_m_soucent_02","a_f_m_tourist_01","a_f_m_trampbeac_01","a_m_m_hasjew_01","a_m_m_hillbilly_01","a_m_m_hillbilly_02","a_m_m_indian_01","a_m_m_ktown_01","a_m_m_malibu_01","a_m_m_mexcntry_01","a_f_m_tramp_01","a_f_o_genstreet_01","a_f_o_indian_01","a_f_o_ktown_01","a_f_o_salton_01","a_f_o_soucent_01","a_f_o_soucent_02","a_m_m_mexlabor_01","a_m_m_og_boss_01","a_m_m_paparazzi_01","a_m_m_polynesian_01","a_m_m_prolhost_01","a_m_m_rurmeth_01","a_m_m_salton_01","a_f_y_beach_01","a_f_y_bevhills_01","a_f_y_bevhills_02","a_f_y_bevhills_03","a_f_y_bevhills_04","a_f_y_business_01","a_f_y_business_02","a_m_m_salton_02","a_m_m_salton_03","a_m_m_salton_04","a_m_m_skater_01","a_m_m_skidrow_01","a_m_m_socenlat_01","a_m_m_soucent_01","a_f_y_business_03","a_f_y_business_04","a_f_y_eastsa_01","a_f_y_eastsa_02","a_f_y_eastsa_03","a_f_y_epsilon_01","a_f_y_fitness_01","a_m_m_soucent_02","a_m_m_soucent_03","a_m_m_soucent_04","a_m_m_stlat_02","a_m_m_tennis_01","a_m_m_tourist_01","a_m_m_trampbeac_01","a_f_y_fitness_02","a_f_y_genhot_01","a_f_y_golfer_01","a_f_y_hiker_01","a_f_y_hippie_01","a_f_y_hipster_01","a_f_y_hipster_02","a_m_m_tramp_01","a_m_m_tranvest_01","a_m_m_tranvest_02","a_m_o_acult_01","a_m_o_acult_02","a_m_o_beach_01","a_m_o_genstreet_01","a_f_y_hipster_03","a_f_y_hipster_04","a_f_y_indian_01","a_f_y_juggalo_01","a_f_y_runner_01","a_f_y_rurmeth_01","a_f_y_scdressy_01","a_m_o_ktown_01","a_m_o_salton_01","a_m_o_soucent_01","a_m_o_soucent_02","a_m_o_soucent_03","a_m_o_tramp_01","a_m_y_acult_01","a_f_y_skater_01","a_f_y_soucent_01","a_f_y_soucent_02","a_f_y_soucent_03","a_f_y_tennis_01","a_f_y_topless_01","a_f_y_tourist_01","a_m_y_acult_02","a_m_y_beachvesp_01","a_m_y_beachvesp_02","a_m_y_beach_01","a_m_y_beach_02","a_m_y_beach_03","a_m_y_bevhills_01","a_f_y_tourist_02","a_f_y_vinewood_01","a_f_y_vinewood_02","a_f_y_vinewood_03","a_f_y_vinewood_04","a_f_y_yoga_01","cs_tracydisanto","a_m_y_bevhills_02","a_m_y_breakdance_01","a_m_y_busicas_01","a_m_y_business_01","a_m_y_business_02","a_m_y_business_03","a_m_y_cyclist_01","cs_tanisha", "cs_patricia", "cs_mrsphillips", "cs_mrs_thornhill", "cs_natalia", "cs_molly", "cs_movpremf_01","a_m_y_dhill_01","a_m_y_downtown_01","a_m_y_eastsa_01","a_m_y_eastsa_02","a_m_y_epsilon_01","a_m_y_epsilon_02","a_m_y_gay_01","cs_maryann", "cs_michelle", "cs_marnie", "cs_magenta", "cs_janet", "cs_jewelass", "cs_guadalope","a_m_y_gay_02","a_m_y_genstreet_01","a_m_y_genstreet_02","a_m_y_golfer_01","a_m_y_hasjew_01","a_m_y_hiker_01","a_m_y_hippy_01","cs_gurk",  "cs_debra", "cs_denise", "cs_amandatownley",  "cs_ashley", "csb_screen_writer", "csb_stripper_01","a_m_y_hipster_01","a_m_y_hipster_02","a_m_y_hipster_03","a_m_y_indian_01","a_m_y_jetski_01","a_m_y_juggalo_01","a_m_y_ktown_01","csb_stripper_02", "csb_tonya", "csb_maude", "csb_denise_friend", "csb_abigail", "csb_anita", "g_f_y_ballas_01","a_m_y_ktown_02","a_m_y_latino_01","a_m_y_methhead_01","a_m_y_mexthug_01","a_m_y_motox_01","a_m_y_motox_02","a_m_y_musclbeac_01","g_f_y_families_01","g_f_y_lost_01","g_f_y_vagos_01","s_f_m_fembarber","s_f_m_maid_01","s_f_m_shop_high","s_f_m_sweatshop_01","a_m_y_musclbeac_02","a_m_y_polynesian_01","a_m_y_roadcyc_01","a_m_y_runner_01","a_m_y_runner_02","a_m_y_salton_01","a_m_y_skater_01","s_f_y_airhostess_01","s_f_y_bartender_01","s_f_y_baywatch_01","s_f_y_factory_01","s_f_y_hooker_01","s_f_y_hooker_02","s_f_y_hooker_03","a_m_y_skater_02","a_m_y_soucent_01","a_m_y_soucent_02","a_m_y_soucent_03","a_m_y_soucent_04","a_m_y_stbla_01","a_m_y_stbla_02","s_f_y_migrant_01","s_f_y_movprem_01","s_f_y_shop_low","s_f_y_shop_mid","s_f_y_stripperlite","s_f_y_stripper_01","s_f_y_stripper_02","a_m_y_stlat_01","a_m_y_stwhi_01","a_m_y_stwhi_02","a_m_y_sunbathe_01","a_m_y_surfer_01","a_m_y_vindouche_01","a_m_y_vinewood_01","s_f_y_sweatshop_01","u_f_m_corpse_01","u_f_m_miranda","u_f_m_promourn_01","u_f_o_moviestar","u_f_o_prolhost_01","u_f_y_bikerchic","u_f_y_comjane","u_f_y_hotposh_01","u_f_y_jewelass_01","u_f_y_mistress","u_f_y_poppymich","u_f_y_princess","u_f_y_spyactress","a_m_y_vinewood_02","a_m_y_vinewood_03","a_m_y_vinewood_04","a_m_y_yoga_01","csb_anton","csb_ballasog","csb_burgerdrug","csb_car3guy1","csb_car3guy2","csb_chef","csb_chin_goon","csb_cletus", "csb_customer", "csb_fos_rep", "csb_g", "csb_groom", "csb_grove_str_dlr", "csb_hao", "csb_hugh", "csb_imran", "csb_janitor", "csb_ortega", "csb_oscar", "csb_porndudes", "csb_prologuedriver", "csb_ramp_gang",  "csb_ramp_hic", "csb_ramp_hipster", "csb_ramp_mex", "csb_reporter", "csb_roccopelosi", "csb_trafficwarden","cs_bankman", "cs_barry", "cs_beverly", "cs_brad", "cs_carbuyer", "cs_chengsr", "cs_chrisformage", "cs_clay", "cs_dale", "cs_davenorton", "cs_devin", "cs_dom", "cs_dreyfuss", "cs_drfriedlander", "cs_fabien", "cs_floyd", "cs_hunter", "cs_jimmyboston", "cs_jimmydisanto", "cs_joeminuteman", "cs_johnnyklebitz", "cs_josef", "cs_josh", "cs_lazlow", "cs_lestercrest", "cs_lifeinvad_01", "cs_manuel", "cs_martinmadrazo", "cs_milton", "cs_movpremmale", "cs_mrk", "cs_nervousron", "cs_nigel", "cs_old_man1a", "cs_old_man2", "cs_omega", "cs_orleans", "cs_paper", "cs_priest", "cs_prolsec_02", "cs_russiandrunk", "cs_siemonyetarian", "cs_solomon", "cs_stevehains", "cs_stretch", "cs_taocheng", "cs_taostranslator", "cs_tenniscoach", "cs_terry", "cs_tom", "cs_tomepsilon", "cs_wade", "cs_zimbor", "g_m_m_armboss_01","g_m_m_armgoon_01","g_m_m_armlieut_01","g_m_m_chemwork_01","g_m_m_chiboss_01","g_m_m_chicold_01","g_m_m_chigoon_01","g_m_m_chigoon_02","g_m_m_korboss_01","g_m_m_mexboss_01","g_m_m_mexboss_02","g_m_y_armgoon_02","g_m_y_azteca_01","g_m_y_ballaeast_01","g_m_y_ballaorig_01","g_m_y_ballasout_01","g_m_y_famca_01","g_m_y_famdnf_01","g_m_y_famfor_01","g_m_y_korean_01","g_m_y_korean_02","g_m_y_korlieut_01","g_m_y_lost_01","g_m_y_lost_02","g_m_y_lost_03","g_m_y_mexgang_01","g_m_y_mexgoon_01","g_m_y_mexgoon_02","g_m_y_mexgoon_03","g_m_y_pologoon_01","g_m_y_pologoon_02","g_m_y_salvaboss_01","g_m_y_salvagoon_01","g_m_y_salvagoon_02","g_m_y_salvagoon_03","g_m_y_strpunk_01","g_m_y_strpunk_02","hc_driver", "hc_gunman", "hc_hacker", "s_m_m_ammucountry","s_m_m_autoshop_01","s_m_m_autoshop_02","s_m_m_bouncer_01","s_m_m_ciasec_01","s_m_m_cntrybar_01","s_m_m_dockwork_01","s_m_m_doctor_01","s_m_m_fiboffice_02","s_m_m_gaffer_01","s_m_m_gardener_01","s_m_m_gentransport","s_m_m_hairdress_01","s_m_m_highsec_01","s_m_m_highsec_02","s_m_m_janitor","s_m_m_lathandy_01","s_m_m_lifeinvad_01","s_m_m_linecook","s_m_m_lsmetro_01","s_m_m_mariachi_01","s_m_m_migrant_01","s_m_m_movprem_01","s_m_m_movspace_01","s_m_m_pilot_01","s_m_m_pilot_02","s_m_m_postal_01","s_m_m_postal_02","s_m_m_scientist_01","s_m_m_strperf_01","s_m_m_strpreach_01","s_m_m_strvend_01","s_m_m_trucker_01","s_m_m_ups_01","s_m_m_ups_02","s_m_o_busker_01","s_m_y_airworker","s_m_y_ammucity_01","s_m_y_armymech_01","s_m_y_autopsy_01","s_m_y_barman_01","s_m_y_baywatch_01","s_m_y_busboy_01","s_m_y_chef_01","s_m_y_clown_01","s_m_y_construct_01","s_m_y_construct_02","s_m_y_dealer_01","s_m_y_devinsec_01","s_m_y_dockwork_01","s_m_y_dwservice_01","s_m_y_dwservice_02","s_m_y_factory_01","s_m_y_garbage","s_m_y_grip_01","s_m_y_mime","s_m_y_pestcont_01","s_m_y_pilot_01","s_m_y_prismuscl_01","s_m_y_prisoner_01","s_m_y_robber_01","s_m_y_shop_mask","s_m_y_strvend_01","s_m_y_uscg_01","s_m_y_valet_01","s_m_y_waiter_01","s_m_y_winclean_01","s_m_y_xmech_01","s_m_y_xmech_02","u_m_m_aldinapoli","u_m_m_bankman","u_m_m_bikehire_01","u_m_m_fibarchitect","u_m_m_filmdirector","u_m_m_glenstank_01","u_m_m_griff_01","u_m_m_jesus_01","u_m_m_jewelsec_01","u_m_m_jewelthief","u_m_m_markfost","u_m_m_partytarget","u_m_m_promourn_01","u_m_m_rivalpap","u_m_m_spyactor","u_m_m_willyfist","u_m_o_finguru_01","u_m_o_taphillbilly","u_m_o_tramp_01","u_m_y_abner","u_m_y_antonb","u_m_y_babyd","u_m_y_baygor","u_m_y_burgerdrug_01","u_m_y_chip","u_m_y_cyclist_01","u_m_y_fibmugger_01","u_m_y_guido_01","u_m_y_gunvend_01","u_m_y_hippie_01","u_m_y_imporage","u_m_y_justin","u_m_y_mani","u_m_y_militarybum","u_m_y_paparazzi","u_m_y_party_01","u_m_y_pogo_01","u_m_y_prisoner_01","u_m_y_proldriver_01","u_m_y_rsranger_01","u_m_y_sbike","u_m_y_staggrm_01","u_m_y_tattoo_01" }

local vehColours = {
    {"Black", 0},
    {"Silver", 4},
    {"Red", 27},
    {"Hot Pink", 135},
    {"Orange", 38},
    {"Yellow", 88},
    {"Lime Green", 92},
    {"Blue", 64},
    {"Chocolate Brown", 96},
    {"Midnight Purple", 142},
    {"Gold", 99},
    {"Ice White", 111},
}

xnRace.VehicleClasses = {
    --[[["Boats"] = {
        "dinghy",
        "jetmax",
        "seashark",
        "speeder",
        "squalo",
        "suntrap",
        "tropic",
    },
    ["Cycles"] = {
        "bmx",
        "cruiser",
        "tribike2",
        "scorcher",
        "tribike3",
        "tribike",
    },
    ["Helicopters"] = {
        "annihilator",
        "buzzard2",
        "cargobob",
        "frogger",
        "maverick",
        "polmav",
        "savage",
        "swift",
        "valkyrie",
    },
    ["Planes"] = {
        "cuban800",
        "dodo",
        "duster",
        "luxor",
        "stunt",
        "mammatus",
        "miljet",
        "shamal",
        "velum",
        "vestra",
    },
    ["Jets"] = {
        "besra",
        "hydra",
        "lazer",
    },]]
    ["Compacts"] = {
        "blista",
        "dilettante",
        "issi2",
        "panto",
        "prairie",
        "rhapsody",
    },
    ["Coupes"] = {
        "COGCABRIO",
        "exemplar",
        "f620",
        "FELON2",
        "jackal",
        "oracle",
        "sentinel",
    },
    ["Bikes"] = {
        "akuma",
        "bagger",
        "bati",
        "bati2",
        "blazer",
        "carbonrs",
        "daemon",
        "double",
        "enduro",
        "hakuchou",
        "innovation",
        "lectro",
        "nemesis",
        "pcj",
        "ruffian",
        "sanchez2",
        "sanchez",
        "sovereign",
        "thrust",
        "vader",
    },
    ["Mucle"] = {
        "blade",
        "buccanee",
        "dominator",
        "dukes",
        "gauntlet",
        "hotknife",
        "phoenix",
        "picador",
        "ratloader2",
        "ruiner",
        "sabregt",
        "slamvan",
        "stalion",
        "vigero",
    },
    ["OffRoad"] = {
        "baller",
        "bifta",
        "blazer",
        "bodhi2",
        "dubsta",
        "dloader",
        "dune",
        "guardian",
        "bfinjection",
        "insurgent2",
        "kalahari",
        "marshall",
        "mesa",
        "paradise",
        "patriot",
        "rebel2",
        "sanchez2",
        "sanchez",
        "sandking",
        "sandking2",
        "monster",
        "tornado4",
    },
    ["Sedans"] = {
        "asea",
        "asterope",
        "fugitive",
        "glendale",
        "premier",
        "primo",
        "schafter2",
        "stanier",
        "superd",
        "surge",
        "tailgater",
        "warrener",
        "washington",
    },
    ["Sports"] = {
        "ninef2",
        "alpha",
        "banshee",
        "banshee",
        "blista2",
        "CARBONIZ",
        "comet2",
        "coquette",
        "elegy2",
        "feltzer",
        "furoregt",
        "fusilade",
        "jester",
        "jester2",
        "khamelion",
        "kuruma",
        "kuruma2",
        "massacro",
        "massacro2",
        "rapidgt2",
        "sultan",
    },
    ["Classics"] = {
        "casco",
        "coquette2",
        "monroe",
        "pigalle",
        "btype",
        "stinger",
        "ztype",
    },
    ["Super"] = {
        "adder",
        "bullet",
        "cheetah",
        "entityxf",
        "infernus",
        "turismor",
        "vacca",
        "voltic",
        "zentorno",
    },
    ["SUV"] = {
        "BALLER",
        "BALLER2",
        "BJXL",
        "cavalcade2",
        "crusader",
        "dubsta",
        "granger",
        "gresley",
        "huntley",
        "landstalker",
        "mesa",
        "pranger",
        "RADI",
        "seminole",
        "serrano",
    },
    ["Utility"] = {
        "airtug",
        "caddy",
        "faggio2",
        "tractor2",
        "mower",
    },
    ["Vans"] = {
        "boxville4",
        "burrito2",
        "camper",
        "speedo2",
        "gburrito2",
        "journey",
        "pony",
        "rumpo",
        "surfer",
        "youga",
    },
    ["Industrial"] = {
        "guardian",
        "bulldozer",
        "dump",
        "flatbed",
        "mixer",
        "rubble",
        "tiptruck",
    }
}

xnRace.VehicleImages = json.decode('["adder":"lgm_default","akuma":"sssa_default","alpha":"lgm_dlc_business","asea":"sssa_dlc_business","bagger":"sssa_dlc_biker","baller2":"sssa_default","banshee":"lgm_default","bati":"sssa_default","bati2":"sssa_default","besra":"elt_dlc_pilot","bifta":"sssa_default","blade":"sssa_dlc_heist","blazer":"sssa_default","blista2":"sssa_dlc_mp_to_sp","bmx":"pandm_default","bodhi2":"sssa_default","boxville4":"candc_default","bullet":"lgm_default","carboniz":"lgm_default","cargobob":"candc_default","casco":"lgm_dlc_heist","cheetah":"lgm_default","comet2":"lgm_default","coquette":"lgm_default","coquette2":"lgm_dlc_pilot","cruiser":"pandm_default","crusader":"candc_default","cuban800":"elt_default","dodo":"elt_default","double":"sssa_default","dukes":"sssa_dlc_mp_to_sp","dump":"candc_default","dune":"sssa_default","duster":"elt_default","elegy2":"lgm_default","enduro":"sssa_dlc_heist","entityxf":"lgm_default","exemplar":"lgm_default","f620":"sssa_dlc_business2","felon2":"sssa_default","feltzer":"lgm_default","frogger":"elt_default","fugitive":"sssa_default","fusilade":"sssa_dlc_business2","gauntlet":"sssa_default","gburrito2":"sssa_dlc_heist","glendale":"sssa_dlc_hipster","granger":"sssa_dlc_business","gresley":"sssa_dlc_heist","guardian":"sssa_dlc_heist","hotknife":"lgm_default","huntley":"lgm_dlc_business2","hydra":"candc_default","infernus":"lgm_default","innovation":"sssa_dlc_heist","insurgent2":"candc_default","issi2":"sssa_default","jackal":"sssa_dlc_heist","jester":"lgm_dlc_business","jester2":"sssa_dlc_christmas_2","jetmax":"dock_default","journey":"candc_default","kalahari":"sssa_default","kuruma":"sssa_dlc_heist","kuruma2":"sssa_dlc_heist","landstalker":"sssa_dlc_heist","lazer":"candc_smuggler","lectro":"lgm_dlc_heist","luxor":"elt_default","mammatus":"elt_default","marshall":"candc_default","massacro":"lgm_dlc_business2","massacro2":"sssa_dlc_christmas_2","maverick":"elt_default","mesa":"candc_default","miljet":"elt_dlc_pilot","monroe":"lgm_default","monster":"candc_default","nemesis":"sssa_dlc_heist","ninef2":"lgm_default","oracle":"sssa_default","panto":"sssa_dlc_hipster","paradise":"sssa_default","pcj":"sssa_default","picador":"sssa_dlc_hipster","pigalle":"sssa_dlc_hipster","premier":"sssa_dlc_business","primo":"sssa_dlc_hipster","radi":"sssa_dlc_business","rapidgt2":"lgm_default","rebel2":"sssa_dlc_hipster","rhapsody":"sssa_dlc_hipster","ruffian":"sssa_default","rumpo":"sssa_dlc_heist","sanchez":"sssa_default","sanchez2":"sssa_default","sandking":"sssa_default","savage":"candc_default","schafter2":"sssa_dlc_heist","scorcher":"pandm_default","seashark":"dock_default","seminole":"sssa_dlc_heist","sentinel":"sssa_dlc_business2","shamal":"elt_default","slamvan":"sssa_dlc_christmas_2","sovereign":"sssa_dlc_independence","speeder":"dock_default","squalo":"dock_default","stanier":"sssa_dlc_business","stinger":"lgm_default","stunt":"elt_default","suntrap":"dock_default","superd":"lgm_default","surfer":"sssa_dlc_hipster","surge":"sssa_dlc_heist","swift":"elt_dlc_pilot","tailgater":"sssa_dlc_hipster","thrust":"lgm_dlc_business2","tribike":"pandm_default","tribike2":"pandm_default","tribike3":"pandm_default","tropic":"dock_default","turismor":"lgm_dlc_business","vacca":"lgm_default","vader":"sssa_default","valkyrie":"candc_default","velum":"elt_default","vestra":"elt_dlc_business","vigero":"sssa_default","warrener":"sssa_dlc_hipster","youga":"sssa_dlc_hipster","zentorno":"lgm_dlc_business2","ztype":"lgm_default"]')
